#!/bin/bash

PLAYER=$1

# mouse input
case $BLOCK_BUTTON in
    1) playerctl --player=$1 play-pause ;;
    4) playerctl --player=$1 next ;;
    5) playerctl --player=$1 previous ;;
esac

# position
TIME=$(playerctl position)
# cast to int
TIME=${TIME%.*}
MINUTE=$(($TIME / 60))
SECOND=$(($TIME % 60))

# if seconds < 10, prefix 0
if [ "$SECOND" -lt "10" ] ; then
    SECOND="0$SECOND"
fi

STATUS=$(playerctl status)

# print
if [ $STATUS = "Playing" ] ; then
    echo " $(playerctl metadata artist) - $(playerctl metadata title) - $MINUTE:$SECOND"
elif [ $STATUS = "Paused" ] ; then
    echo " $(playerctl metadata artist) - $(playerctl metadata title) - $MINUTE:$SECOND"
else
    echo "No Artist - No Title - 00:00"
fi
